<?php
/**
 * @file
 * google_analytics_counter_queue.install
 */

/**
 * Implements hook_install().
 */
function google_analytics_counter_queue_install() {
  variable_set('google_analytics_counter_queue_cache_lifetime', NULL);
  variable_set('google_analytics_counter_queue_google_analytics_oauth_consumer_key', NULL);
  variable_set('google_analytics_counter_queue_google_analytics_oauth_consumer_secret', NULL);
  variable_set('google_analytics_counter_queue_google_analytics_oauth_token', NULL);
  variable_set('google_analytics_counter_queue_google_analytics_oauth_token_secret', NULL);
  variable_set('google_analytics_counter_queue_google_analytics_profile_id', NULL);
  variable_set('google_analytics_counter_queue_execute_queues_on_cron', TRUE);
  variable_set('google_analytics_counter_queue_google_analytics_data_query_max_results', '1000');
  variable_set('google_analytics_counter_queue_google_analytics_queue_item_threshold', '3');
  variable_set('google_analytics_counter_queue_update_statistics_node_counter', 1);
  variable_set('google_analytics_counter_queue_queue_ignored_paths', implode("\n", array('node/*/edit')));
  variable_set('google_analytics_counter_queue_queue_process_admin_paths', 0);
  variable_set('google_analytics_counter_queue_google_analytics_data_query_start_date', '2005-01-01');
  variable_set('google_analytics_counter_queue_queue_process_multiple', 1);
  // Drupal's queue API requires that any custom implemented queue classes are
  // defined as variables, allowing the queue class to be retrieved dynamically
  // using the variable `queue_class_{queue_name}`. This is primarily used
  // with the DrupalQueue::get() method.
  variable_set('queue_class_google_analytics_counter_queue', 'GoogleAnalyticsCounterQueueQueue');
  variable_set('queue_class_google_analytics_counter_priority_queue', 'GoogleAnalyticsCounterQueuePriorityQueue');
  // During installation, we will ensure that the statistics module, if enabled,
  // has its content view increment turned off.
  if (module_enabled('statistics')) {
    variable_set('statistics_count_content_views', 0);
  }
}

/**
 * Implements hook_uninstall().
 */
function google_analytics_counter_queue_uninstall() {
  variable_del('google_analytics_counter_queue_cache_lifetime');
  variable_del('google_analytics_counter_queue_google_analytics_oauth_consumer_key');
  variable_del('google_analytics_counter_queue_google_analytics_oauth_consumer_secret');
  variable_del('google_analytics_counter_queue_google_analytics_oauth_token');
  variable_del('google_analytics_counter_queue_google_analytics_oauth_token_secret');
  variable_del('google_analytics_counter_queue_google_analytics_profile_id');
  variable_del('google_analytics_counter_queue_execute_queues_on_cron');
  variable_del('google_analytics_counter_queue_google_analytics_data_query_max_results');
  variable_del('google_analytics_counter_queue_google_analytics_queue_item_threshold');
  variable_del('google_analytics_counter_queue_update_statistics_node_counter');
  variable_del('google_analytics_counter_queue_queue_ignored_paths');
  variable_del('google_analytics_counter_queue_queue_process_admin_paths');
  variable_del('google_analytics_counter_queue_google_analytics_data_query_start_date');
  variable_del('google_analytics_counter_queue_queue_process_multiple');
  // Delete Drupal core's queue related variables to perform complete cleanup.
  variable_del('queue_class_google_analytics_counter_queue');
  variable_del('queue_class_google_analytics_counter_priority_queue');
}

/**
 * Implements hook_schema().
 */
function google_analytics_counter_queue_schema() {
  $schema = array();
  // Because both the general and priority queues have identical storage tables,
  // we will simply create the database table schema once and assign to the
  // $schema variable with correct table names.
  $queue_table_schema = array(
    'description' => 'Stores queue items and their data for processing.',
    'fields' => array(
      'item_id' => array(
        'type' => 'serial',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'description' => 'Primary Key: Unique item ID.',
      ),
      'path' => array(
        'type' => 'varchar',
        'length' => '255',
        'not null' => TRUE,
        'default' => '',
        'description' => 'The path for processing.',
      ),
      'total_records' => array(
        'type' => 'int',
        'size' => 'normal',
        'unsigned' => TRUE,
        'not null' => FALSE,
        'default' => 0,
        'description' => 'The total number of records that require processing.',
      ),
      'remaining_records' => array(
        'type' => 'int',
        'size' => 'normal',
        'unsigned' => TRUE,
        'not null' => FALSE,
        'default' => 0,
        'description' => 'The remaining number of records to be processed.',
      ),
      'expire' => array(
        'type' => 'int',
        'not null' => TRUE,
        'unsigned' => TRUE,
        'default' => 0,
        'description' => 'Timestamp when the claim lease expires on the item.',
      ),
      'created' => array(
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
        'description' => 'Timestamp when the item was created.',
      ),
      'attempts' => array(
        'type' => 'int',
        'not null' => TRUE,
        'unsigned' => TRUE,
        'default' => 0,
        'description' => 'Number of attempts to process where an error occurred or no data returned.',
      ),
      'weight' => array(
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
        'description' => 'Queue item weight, used to determine the order of processing.',
      ),
    ),
    'primary key' => array('item_id'),
  );
  $schema['google_analytics_counter_queue_queue'] = $queue_table_schema;
  $schema['google_analytics_counter_queue_priority_queue'] = $queue_table_schema;
  $schema['google_analytics_counter_queue_statistics'] = array(
    'description' => 'Access statistic sums for paths.',
    'fields' => array(
      'statistic_id' => array(
        'type' => 'serial',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'description' => 'Primary Key: Unique identifier for path statistics.',
      ),
      'created' => array(
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
        'description' => 'The timestamp in which this path was first created.',
      ),
      'updated' => array(
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
        'description' => 'The timestamp in which this path was last updated.',
      ),
      'path' => array(
        'type' => 'varchar',
        'length' => '1024',
        'not null' => TRUE,
        'unique' => TRUE,
        'description' => 'The path. This is a normalized Drupal path.',
      ),
      'totalcount' => array(
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
        'size' => 'big',
        'description' => 'The total number of times this path has been viewed.',
      ),
    ),
    'primary key' => array('statistic_id'),
  );
  $schema['google_analytics_counter_queue_statistics_path'] = array(
    'description' => '',
    'fields' => array(
      'id' => array(
        'type' => 'serial',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'description' => 'Primary Key: Unique identifier for individual path statistics.',
      ),
      'statistic_id' => array(
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
        'description' => 'The statistic id which this path is related to.',
      ),
      'created' => array(
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
        'description' => 'The timestamp in which this path was first created.',
      ),
      'updated' => array(
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
        'description' => 'The timestamp in which this path was last updated.',
      ),
      'path' => array(
        'type' => 'varchar',
        'length' => '1024',
        'not null' => TRUE,
        'unique' => TRUE,
        'description' => 'The path.',
      ),
      'count' => array(
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
        'size' => 'big',
        'description' => 'The total number of times this path has been viewed.',
      ),
    ),
    'primary key' => array('id'),
    'foreign keys' => array(
      'google_analytics_counter_queue_statistics' => array('statistic_id' => 'statistic_id'),
    ),
  );
  return $schema;
}

/**
 * Implements hook_requirements().
 */
function google_analytics_counter_queue_requirements($phase) {
  $requirements = array();
  if ('runtime' == $phase) {
    $requirements['google_analytics_counter_queue_authentication'] = array(
      'title' => t('Google Analytics Counter Queue - Authentication'),
      'description' => t('Google Analytics Counter Queue requires that a Google Analytics account is connected and authenticated to read reports allowing the module to fetch data and process paths to update the number of view counts. You can connect an account !link.', array(
        '!link' => l(t('here'), 'admin/config/system/google-analytics-counter-queue/authentication'),
      )),
    );

    $client = google_analytics_counter_queue_google_analytics_client();
    if ($client->isAuthenticated()) {
      $requirements['google_analytics_counter_queue_authentication']['value'] = t('Authenticated');
      $requirements['google_analytics_counter_queue_authentication']['severity'] = REQUIREMENT_OK;
    }
    else {
      $requirements['google_analytics_counter_queue_authentication']['value'] = t('Not authenticated');
      $requirements['google_analytics_counter_queue_authentication']['severity'] = REQUIREMENT_ERROR;
    }

    if (google_analytics_counter_queue_update_statistics_node_counter()) {
      $statistics_count_content_views = variable_get('statistics_count_content_views', 0);
      $requirements['google_analytics_counter_queue_statistics'] = array(
        'title' => t('Google Analytics Counter Queue and Statistics'),
        'description' => t('Google Analytics Counter Queue requires that the Drupal core Statistics module does not track content views <em>if</em> the %update_var_name is enabled.', array(
          '%update_var_name' => t('Update node statistics counter'),
        )),
      );
      if (!$statistics_count_content_views) {
        $requirements['google_analytics_counter_queue_statistics']['value'] = t('OK');
        $requirements['google_analytics_counter_queue_statistics']['severity'] = REQUIREMENT_OK;
      }
      else {
        $requirements['google_analytics_counter_queue_statistics']['value'] = t('Error');
        $requirements['google_analytics_counter_queue_statistics']['severity'] = REQUIREMENT_ERROR;
      }
    }
  }
  return $requirements;
}
